
export const GET_BREEDS = "CATS/GET_BREEDS";
export const LIST_CATS = "CATS/LIST_CATS";
export const LOAD_MORE_CATS = "CATS/LOAD_MORE_CATS";
export const SET_CURRENT_BREED = "CATS/SET_CURRENT_BREED";
export const GET_CURRENT_CAT = "CATS/GET_CURRENT_CAT";